name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Init
      run: cargo install sqlx-cli && sqlx database create && sqlx migrate run
    - name: Build
      run: cargo build --verbose
    - name: clippy check
      run: cargo clippy
    - name: Run tests
      run: cargo test --verbose
